---
- name: install privoxy
  apt:
    pkg=privoxy
    state=present

- name: configure privoxy
  template: src=config
            dest=/etc/privoxy/config
            owner=root group=root mode=0644

- name: restart privoxy
  service:
    name=privoxy
    state=restarted

- name: start privoxy
  service:
    name=privoxy
    state=started
    enabled=true
