---
- hosts: runner
  gather_facts: true
  become: true
  become_method: sudo
  become_user: root
  remote_user: "{{ user_name }}"
  roles:
   - install_GitLab-Runner  # GitLab Runner https://github.com/riemers/ansible-gitlab-runner/

  environment:
     http_proxy: http://{{ domain_name }}:8118
     https_proxy: http://{{ domain_name }}:8118
